dbfilename redis_queue.rdb
dir /home/jamshed/Desktop/atikincampus/atikincampus/config/pids
pidfile /home/jamshed/Desktop/atikincampus/atikincampus/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/jamshed/Desktop/atikincampus/atikincampus/config/redis_queue.acl
